"""Pydantic v2 data models shared across CodeMemory modules."""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class FileInfo(BaseModel):
    """Metadata about a single source file."""

    path: str = Field(description="Absolute or repo-relative path to the file.")
    language: str | None = Field(
        default=None, description="Detected programming language name."
    )
    size_bytes: int = Field(default=0, description="File size in bytes.")
    hash: str | None = Field(
        default=None, description="SHA-256 hex digest of file contents."
    )
    last_scanned: float | None = Field(
        default=None,
        description="Unix timestamp of when the file was last indexed.",
    )
    summary: str | None = Field(
        default=None, description="Human-readable summary generated by the summarizer."
    )

    # Compatibility fields for tests and old APIs
    content: str | None = Field(default=None, description="Raw content of the file (optional).")
    symbols: list[SymbolInfo] | None = Field(default=None, description="Symbols in this file (optional).")
    size: int | None = Field(default=None, description="Compatibility alias for size_bytes.")
    last_modified: float | None = Field(default=None, description="Compatibility alias for last_scanned.")

    def model_post_init(self, __context: Any) -> None:
        """Synchronise compatibility fields with core fields."""
        if self.size is not None and self.size_bytes == 0:
            self.size_bytes = self.size
        elif self.size_bytes != 0 and self.size is None:
            self.size = self.size_bytes

        if self.last_modified is not None and self.last_scanned is None:
            self.last_scanned = self.last_modified
        elif self.last_scanned is not None and self.last_modified is None:
            self.last_modified = self.last_scanned


class SymbolInfo(BaseModel):
    """A named code symbol extracted from a source file."""

    name: str = Field(description="Identifier name of the symbol.")
    kind: Literal["class", "function", "method", "import", "variable"] = Field(
        description="Semantic kind of the symbol."
    )
    file_path: str = Field(default="", description="Path of the file containing this symbol.")
    start_line: int = Field(default=0, description="1-based starting line number.")
    end_line: int = Field(default=0, description="1-based ending line number (inclusive).")
    signature: str | None = Field(
        default=None, description="Full declaration/signature text."
    )
    docstring: str | None = Field(
        default=None, description="Documentation string if available."
    )
    parent_name: str | None = Field(
        default=None,
        description="Name of the parent symbol (e.g. class name for a method).",
    )
    # Compatibility field for tests
    line: int | None = Field(default=None, description="Compatibility alias for start_line.")

    def model_post_init(self, __context: Any) -> None:
        """Synchronise compatibility fields."""
        if self.line is not None:
            if self.start_line == 0:
                self.start_line = self.line
            if self.end_line == 0:
                self.end_line = self.line


class RelationshipInfo(BaseModel):
    """A directed relationship between two code artifacts."""

    from_file: str = Field(description="Source file path.")
    to_file: str = Field(description="Target file path.")
    from_symbol: str | None = Field(
        default=None, description="Originating symbol name (optional)."
    )
    to_symbol: str | None = Field(
        default=None, description="Target symbol name (optional)."
    )
    rel_type: Literal["imports", "calls", "inherits", "uses", "exports"] = Field(
        description="Type of relationship."
    )


class ScanResult(BaseModel):
    """Full extraction result for a single source file."""

    file_info: FileInfo
    symbols: list[SymbolInfo] = Field(default_factory=list)
    imports: list[str] = Field(
        default_factory=list,
        description="Raw import strings found in the file.",
    )
    exports: list[str] = Field(
        default_factory=list,
        description="Names or paths explicitly exported from the file.",
    )


class ProjectSummary(BaseModel):
    """High-level summary of an entire indexed repository."""

    total_files: int = Field(default=0)
    total_symbols: int = Field(default=0)
    languages: dict[str, int] = Field(
        default_factory=dict,
        description="Mapping of language name to file count.",
    )
    architecture_layers: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Detected architecture layers and their representative modules.",
    )
    key_modules: list[str] = Field(
        default_factory=list,
        description="Paths of the most connected/important files.",
    )
    last_scanned: float | None = Field(
        default=None, description="Unix timestamp of the most recent full scan."
    )


class RetrievalResult(BaseModel):
    """A single ranked result from a context retrieval query."""

    file_path: str = Field(description="Path of the matching file.")
    score: float = Field(description="Relevance score (higher is better).")
    reason: str = Field(
        default="", description="Human-readable explanation of why this file matched."
    )
    symbols: list[str] = Field(
        default_factory=list,
        description="Names of relevant symbols within the file.",
    )
    snippet: str | None = Field(
        default=None, description="Short code or text excerpt from the file."
    )
